baseURL: "/"
title: Arusekk blog
theme: papermod

# Home page
params:
  homeInfoParams:
    Title: Welcome
    Content: My name is Arusekk.  Not a real name, but I find it the most real for me online.  This is a blog where I write about computer programming and some unpopular opinions.

  socialIcons:
    - name: Rss
      url: posts/index.xml
    - name: GitHub
      url: https://github.com/Arusekk
    - name: GitLab
      url: https://gitlab.com/Arusekk
    - name: LinkedIn
      url: https://www.linkedin.com/in/arusekk/
    - name: Matrix
      url: https://matrix.to/#/@arusekk:matrix.org
    - name: CTFtime
      url: https://ctftime.org/user/102157
    - name: StackOverflow
      url: https://stackoverflow.com/users/3869724/arusekk
    - name: Mastodon
      url: https://infosec.exchange/@Arusekk

# Navbar
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Contact
      url: /contact/
      weight: 3
    - name: Blogroll
      url: /blogroll/
      weight: 4
    - name: Feed
      url: /posts/index.xml
      weight: 5

# Other settings
paginate: 5
