name: Build and deploy to GitHub Pages
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run:  hugo

      - name: Legacy links
        run:  ./mklinks.sh

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: public
        if: github.ref == 'refs/heads/develop'
